---
    # First, check if the SSH config file exists
    - name: Backup the existing SSH configuration file
      stat: path=/etc/ssh/sshd_config
      register: config_status

    # Backup the SSH config file (if it exists)
    - name: Copy the sshd_config to sshd_config.orig
      copy: remote_src=True
            src=/etc/ssh/sshd_config
            dest=/etc/ssh/sshd_config.orig

      notify:
        - restart_sshd
