---
    # Install Mariadb and the mysql-related packages
    - name: Install MariaDB
      yum: name=mariadb           
           state=latest
    - name: Install MariaDB server
      yum: name=mariadb-server           
           state=latest
    - name: Install MariaDB devel
      yum: name=mariadb-devel           
           state=latest
    - name: Install MySQL-python
      yum: name=MySQL-python           
           state=latest
    - name: Install php-mysql
      yum: name=php-mysql           
           state=latest

     # Enable the MariaDB service
    - name: Enable MariaDB
      systemd: name=mariadb
               state=started
               enabled=yes

      notify:
        - open_mariadb_port
        - restart_mariadb
