---
    # Begin mysql_secure_installation
    - name: Set a new root password
      mysql_user: check_implicit_admin=yes
                  login_user=root
                  login_password={{ mysql_root_password }}
                  user=root
                  password={{ mysql_root_password }}
                  host={{ item }}
                  priv='*.*:ALL,GRANT'
      with_items:
        - localhost
        - 127.0.0.1
      notify:
        - restart_mariadb

    - name: Remove anonymous MySQL user from localhost
      mysql_user: check_implicit_admin=yes
                  login_user=root
                  login_password={{ mysql_root_password }}
                  login_host={{ item }}
                  user=""
                  state=absent
      with_items:
        - localhost
        - 127.0.0.1
      notify: 
        - restart_mariadb
  
    - name: Remove test database
      mysql_db: login_user=root
                login_password={{ mysql_root_password }}
                login_host={{ item }}
                name=test
                state=absent
      with_items:
        - localhost
        - 127.0.0.1
      notify:
        - restart_mariadb
